FROM python:3.8-slim

WORKDIR /app

COPY ./. /app

RUN pip install psycopg2-binary # is not automatically being put into requirements
RUN pip install -r requirements.txt

CMD ["python","-u","plot.py"]
